kitakami: Fix build with GCC
since C++11 introduced user-defined literals then
this patch adds spaces between string literals and macros
and fix build process using GCC

error: unable to find string literal operator 'operator"" PRId64'

Signed-off-by: Humberto Borba <humberos@gmail.com>